// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiisrzphzrbmdetctgea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpaXNyenBoenJibWRldGN0Z2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTAxOTIsImV4cCI6MjA2OTgyNjE5Mn0.CORCJG02H00K32ybO13BNNrY8uNUjne5ydS1ONCQE2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});